[package]
name = "mineflake-cli"
version = "0.1.0"
edition = "2021"
authors = ["Egor Ternovoy <cofob@riseup.net>"]
description = "Mineflake CLI tools"
readme = "README.md"
repository = "https://git.frsqr.xyz/firesquare/mineflake-cli"
homepage = "https://git.frsqr.xyz/firesquare/mineflake"
license = "GPL-3.0-only"
keywords = ["cli", "mineflake", "nix", "nixos"]

[dependencies]
# CLI parsing
clap = { version = "3.2.20", features = [ "derive" ] }

# Serde-related
serde = "1.0.144"
serde_yaml = "0.9.11"
serde_json = "1.0"
toml = "0.5.9"

[profile.dev]
codegen-units = 256
incremental = true
opt-level = 0
debug = true

[profile.release]
debug-assertions = false
overflow-checks = false
incremental = false
opt-level = 3
panic = 'unwind'
debug = false
strip = true
lto = true
