pipeline:
  mk-docs:
    image: ghcr.io/cofob/nmd
    commands:
      - nix-build -A docs.html
      - cp -r result/share/doc/mineflake/ docs-result/
  mk-car:
    image: cofob/ipfs-tools
    commands:
      - ipfs-car --wrapWithDirectory false --pack docs-result/ --output docs.car
  pin-web3:
    image: cofob/node-hugo-jq
    commands:
      - |
        curl -X 'POST' \
          'https://api.web3.storage/car' \
          -H 'accept: application/json' \
          -H "Authorization: Bearer $JWT" \
          -H 'Content-Type: application/vnd.ipld.car' \
          --data-binary '@docs.car' | jq -r .cid > cid.txt
      - echo "https://$(cat cid.txt).ipfs.ipfsqr.ru/"
    secrets: [ JWT ]
  update-dnslink:
    image: cofob/cli4
    commands:
      - cli4 --delete "/zones/:ipfsqr.ru/dns_records/:_dnslink.mineflake.ipfsqr.ru" || true
      - cli4 --post "name=_dnslink.mineflake.ipfsqr.ru" type=TXT content="dnslink=/ipfs/$(cat cid.txt)" "/zones/:ipfsqr.ru/dns_records"
    secrets: [ CLOUDFLARE_API_KEY, CLOUDFLARE_ACCOUNT_ID ]

branches: main
