pipeline:
  mk-docs:
    image: ghcr.io/cofob/nmd
    commands:
      - nix-build -A docs.html
      - cp -r result/share/doc/mineflake/ docs-result/
  pin-cluster:
    image: cofob/ipfs-cluster-ctl
    commands:
      - ipfs-cluster-ctl --host /dns4/rat.frsqr.xyz/tcp/9094 --basic-auth default:$CLUSTER_SECRET add -r --expire-in 2160h --name mineflake-build-$(date +%s) -Q docs-result/ > cid.txt
      - cat cid.txt
      - echo "https://ipfsqr.ru/ipfs/$(cat cid.txt)"
    secrets: [CLUSTER_SECRET]
