pipeline:
  mk-docs:
    image: ghcr.io/cofob/nmd
    commands:
      - nix-build -A docs.html
      - cp -r result/share/doc/mineflake/ docs-result/
  mk-car:
    image: cofob/ipfs-tools
    commands:
      - ipfs-car --wrapWithDirectory false --pack docs-result/ --output docs.car
  pin-web3:
    image: cofob/node-hugo-jq
    commands:
      - |
        curl -X 'POST' \
          'https://api.web3.storage/car' \
          -H 'accept: application/json' \
          -H "Authorization: Bearer $JWT" \
          -H 'Content-Type: application/vnd.ipld.car' \
          --data-binary '@docs.car' | jq -r .cid > cid.txt
      - echo "https://$(cat cid.txt).ipfs.ipfsqr.ru/"
    secrets: [ JWT ]
